spring.application.name=ChickenFightServer
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/chf
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
jwt.secret.key=${JWT_SECRET}
server.address=0.0.0.0
server.port=8081
server.forward-headers-strategy=framework
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect